# Etapa 1: construir o aplicativo Dart
FROM dart:stable AS build

WORKDIR /app
COPY . .

RUN dart pub get
RUN dart compile exe bin/server.dart -o /app/bin/server

# Etapa 2: executar o aplicativo compilado
FROM debian:buster-slim
WORKDIR /app

COPY --from=build /runtime/ /runtime/
COPY --from=build /app/bin/server /app/bin/server

EXPOSE 8080

CMD ["/app/bin/server"]